document.addEventListener('DOMContentLoaded', () => {
    const playerHand = document.getElementById('player-hand');
    const dealerHand = document.getElementById('dealer-hand');
    const message = document.getElementById('message');
    const hitButton = document.getElementById('hit-button');
    const standButton = document.getElementById('stand-button');
    const resetButton = document.getElementById('reset-button');
    const betAmountInput = document.getElementById('bet-amount');
    const placeBetButton = document.getElementById('place-bet');

    let deck = [];
    let playerCards = [];
    let dealerCards = [];
    let playerMoney = 1000;
    let betAmount = 0;

    const suits = ['hearts', 'diamonds', 'clubs', 'spades'];
    const values = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'jack', 'queen', 'king', 'ace'];

    const cardImages = {
        'ace_of_hearts': 'https://via.placeholder.com/100x150.png?text=Ace+of+Hearts',
        '2_of_hearts': 'https://via.placeholder.com/100x150.png?text=2+of+Hearts',
        '3_of_hearts': 'https://via.placeholder.com/100x150.png?text=3+of+Hearts',
        '4_of_hearts': 'https://via.placeholder.com/100x150.png?text=4+of+Hearts',
        '5_of_hearts': 'https://via.placeholder.com/100x150.png?text=5+of+Hearts',
        '6_of_hearts': 'https://via.placeholder.com/100x150.png?text=6+of+Hearts',
        '7_of_hearts': 'https://via.placeholder.com/100x150.png?text=7+of+Hearts',
        '8_of_hearts': 'https://via.placeholder.com/100x150.png?text=8+of+Hearts',
        '9_of_hearts': 'https://via.placeholder.com/100x150.png?text=9+of+Hearts',
        '10_of_hearts': 'https://via.placeholder.com/100x150.png?text=10+of+Hearts',
        'jack_of_hearts': 'https://via.placeholder.com/100x150.png?text=Jack+of+Hearts',
        'queen_of_hearts': 'https://via.placeholder.com/100x150.png?text=Queen+of+Hearts',
        'king_of_hearts': 'https://via.placeholder.com/100x150.png?text=King+of+Hearts',
        'ace_of_diamonds': 'https://via.placeholder.com/100x150.png?text=Ace+of+Diamonds',
        '2_of_diamonds': 'https://via.placeholder.com/100x150.png?text=2+of+Diamonds',
        '3_of_diamonds': 'https://via.placeholder.com/100x150.png?text=3+of+Diamonds',
        '4_of_diamonds': 'https://via.placeholder.com/100x150.png?text=4+of+Diamonds',
        '5_of_diamonds': 'https://via.placeholder.com/100x150.png?text=5+of+Diamonds',
        '6_of_diamonds': 'https://via.placeholder.com/100x150.png?text=6+of+Diamonds',
        '7_of_diamonds': 'https://via.placeholder.com/100x150.png?text=7+of+Diamonds',
        '8_of_diamonds': 'https://via.placeholder.com/100x150.png?text=8+of+Diamonds',
        '9_of_diamonds': 'https://via.placeholder.com/100x150.png?text=9+of+Diamonds',
        '10_of_diamonds': 'https://via.placeholder.com/100x150.png?text=10+of+Diamonds',
        'jack_of_diamonds': 'https://via.placeholder.com/100x150.png?text=Jack+of+Diamonds',
        'queen_of_diamonds': 'https://via.placeholder.com/100x150.png?text=Queen+of+Diamonds',
        'king_of_diamonds': 'https://via.placeholder.com/100x150.png?text=King+of+Diamonds',
        'ace_of_clubs': 'https://via.placeholder.com/100x150.png?text=Ace+of+Clubs',
        '2_of_clubs': 'https://via.placeholder.com/100x150.png?text=2+of+Clubs',
        '3_of_clubs': 'https://via.placeholder.com/100x150.png?text=3+of+Clubs',
        '4_of_clubs': 'https://via.placeholder.com/100x150.png?text=4+of+Clubs',
        '5_of_clubs': 'https://via.placeholder.com/100x150.png?text=5+of+Clubs',
        '6_of_clubs': 'https://via.placeholder.com/100x150.png?text=6+of+Clubs',
        '7_of_clubs': 'https://via.placeholder.com/100x150.png?text=7+of+Clubs',
        '8_of_clubs': 'https://via.placeholder.com/100x150.png?text=8+of+Clubs',
        '9_of_clubs': 'https://via.placeholder.com/100x150.png?text=9+of+Clubs',
        '10_of_clubs': 'https://via.placeholder.com/100x150.png?text=10+of+Clubs',
        'jack_of_clubs': 'https://via.placeholder.com/100x150.png?text=Jack+of+Clubs',
        'queen_of_clubs': 'https://via.placeholder.com/100x150.png?text=Queen+of+Clubs',
        'king_of_clubs': 'https://via.placeholder.com/100x150.png?text=King+of+Clubs',
        'ace_of_spades': 'https://via.placeholder.com/100x150.png?text=Ace+of+Spades',
        '2_of_spades': 'https://via.placeholder.com/100x150.png?text=2+of+Spades',
        '3_of_spades': 'https
